"""Phototools.py constants"""

import enum

MAX_FILES = 9999
INDEX_LENGTH = 4

IMAGE_SUFFIXES = ["*.JPG", "*.JPEG", "*.PNG"]

RENAMING_COMMAND = "rename"
PADDING_COMMAND = "pad"
NEGATIVE_COMMAND = "neg"
MERGE_COMMAND = "merge"

RENAMING_SUFFIX = "_(relative)/"
PADDING_SUFFIX = "_(padded)/"
NEGATIVE_SUFFIX = "_(negative)/"
MERGE_SUFFIX = "_(merged)/"

MAP_COMMAND_TO_SUFFIX = {
    RENAMING_COMMAND : RENAMING_SUFFIX,
    PADDING_COMMAND : PADDING_SUFFIX,
    NEGATIVE_COMMAND : NEGATIVE_SUFFIX,
    MERGE_COMMAND : MERGE_SUFFIX,
    }

MAP_COMMAND_TO_NUM_ARGS = {
    RENAMING_COMMAND : 3,
    PADDING_COMMAND : 4,
    NEGATIVE_COMMAND : 3,
    MERGE_COMMAND : 4,
}

DEFAULT_PAD_COLOUR = (127,127,127)
DEFAULT_MERGE_ROW_COUNT = 1

VALID_COMMANDS = [RENAMING_COMMAND, PADDING_COMMAND, NEGATIVE_COMMAND, MERGE_COMMAND]
DISPLAY_COMMANDS = [RENAMING_COMMAND,
    PADDING_COMMAND,
    NEGATIVE_COMMAND,
    MERGE_COMMAND + "<numRows>"]

ONLY_INTEGERS_REGEX = "^\\d+$"
BLACK_COLOUR = (0,0,0)
WHITE_COLOUR = (255,255,255)
BLACK_COLOUR_ALPHA = (0,0,0,255)
WHITE_COLOUR_ALPHA = (255,255,255,255)

class Error(enum.Enum):
    """Special values for different kinds of execution errors"""
    TOO_FEW_ARGUMENTS = 1
    WRONG_NUM_ARGUMENTS = 2
    INVALID_COMMAND = 3
